base_url = "https://nikrev.com"
build_search_index = false
title = "Nik Revenco 🦀"
description = "My personal blog"

taxonomies = [{ name = "categories" }, { name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "css"
bottom_footnotes = true

[extra]
links = [
  { title = "GitHub", href = "https://github.com/nik-rev" },
  { title = "LinkedIn", href = "https://linkedin.com" },
]
