baseURL = 'https://nikrev.com'
languageCode = 'en-us'
title = 'Nikita Revenco'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
# googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "Personal Website"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I am 18 years old and from England. 🇬🇧

In my free time I contribute to open-source software such as the [Helix Editor](https://github.com/helix-editor/helix/pulls/nik-rev) by fixing bugs and adding new features.

I love learning new concepts and ideas. At the moment I'm learning backend development.

Saying I'm a heavy terminal user is probably an understatement :). I practically live in the command-line. I use NixOS operating system and Helix as my IDE.

Most of my time is spent on reading other people's code which made me realise just how important having clear conventions and readable code is. I care a lot about documentation and automated tests.

So it should come as no surpsise then, that my favorite language is Rust. I've written code in over a dozen other languages, with Rust being both the most enjoyable *and* the most productive language. Honorable mentions include Haskell and TypeScript. I love me a strict type system.

If you'd like to chat, send me an email at `pm@nikrev.com`.
"""

# Collection to display on home
# homeCollectionTitle = 'Posts'
# homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

[[params.social]]
name = "github"
url = "https://github.com/nik-rev"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "projects"
url = "/projects"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
# [params.giscus]
# enable = false
# repo = "nik-rev/nik-rev"
# repoid = "repoId"
# category = "Blog"
# categoryid = "categoryId"
# mapping = "pathname"
# theme = "preferred_color_scheme"
