base_url = "https://carbon.nikrev.com"
build_search_index = false

minify_html = true
output_dir = ".public"
default_language = "en"
author = "Nik Revenco"
title = "Carbon"
description = "A minimalistic Zola theme"

[markdown]
highlight_code = true
highlight_theme = "css"
bottom_footnotes = true
insert_anchor_links = "heading"
smart_punctuation = true

[extra]
show_footer = true
footer_message = "Powered by [Zola](https://github.com/getzola/zola) and [nik-rev/carbon](https://github.com/nik-rev/carbon)"
header_links = [
  { name = "/home", link = "/" },
  "/features",
  "/blog",
  { name = "/installation.md", link = "/installation" },
]
