base_url = "https://nik-rev.github.io/carbon/"
build_search_index = false

minify_html = true
output_dir = ".public"
default_language = "en"
author = "Nik Revenco"
title = "Carbon"
description = "A minimalistic Zola theme"

[markdown]
highlight_code = true
highlight_theme = "css"
bottom_footnotes = true
insert_anchor_links = "heading"
smart_punctuation = true

[extra]
locale = "en_GB"
header_links = [
  { name = "/home", link = "/carbon" },
  { name = "/features", link = "/carbon/features" },
  { name = "/blog", link = "/carbon/blog" },
  { name = "/installation.md", link = "/carbon/installation" },
]
