base_url = "https://nikrev.com"
build_search_index = false

default_language = "en"
author = "Nik Revenco"
title = "Carbon"
description = "A minimalistic Zola theme"

[markdown]
highlight_code = true
highlight_theme = "css"
bottom_footnotes = true
insert_anchor_links = "heading"
smart_punctuation = true

[extra]
header_links = [
  { name = "/home", link = "/" },
  "/features",
  "/blog",
  { name = "/installation.md", link = "/installation" },
]
