base_url = "https://nikrev.com"
build_search_index = false

default_language = "en"
author = "Nik Revenco"
title = "Nik 🦀"
output_dir = ".public"
description = "My personal blog"

[markdown]
highlight_code = true
highlight_theme = "css"
bottom_footnotes = true
insert_anchor_links = "heading"
smart_punctuation = true

[extra]
header_links = [{ name = "/home", link = "/" }, "/blog", "/open-source"]
blog_title = "Nik's Blog 🦀"
