base_url = "https://nikrev.com"
build_search_index = false

default_language = "en"
author = "Nik Revenco"
title = "Nik Revenco 🦀"
output_dir = ".public"
description = "My personal blog"

[markdown]
highlight_code = true
highlight_theme = "css"
bottom_footnotes = true
